# -*- coding: utf-8 -*-
"""List_Comprehension.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eFEoOH-u2z4ubfrHwnGFyqEb-OL2QhpU

23. Add 1 to 10 numbers to a list.
"""

l = [i for i in range (1,11)]
print(l)

"""24. Scaler multiplication on a vector."""

v = [2,3,4]
s = -3
[s*i for i in v]

"""25. Print all the numbers divisible by 5 inn the range of 1 to 50."""

a = [i for i in range(1,51) if i%5==0]
print(a)

"""26. Find languages which starts with letter p."""

lang = ['java','python','php','R','Ruby']
[i for i in lang if i.startswith('p')]

"""27. Adding new list from basket1 and basket2 if the fruit exist in basket1 and also starts with letter "a"."""

basket1 = ['apple','banana','mango','avacado','grapes']
basket2 = ['apple','kiwi','grapes','pineapple','avacado']

[i for i in basket2 if i in basket1 and i.startswith('a')]

"""28. Print a(3,3) matrix usingg list comprehension."""

[[i*j for i in range (1,4)] for j in range(1,4)]

"""29. Cartesian products -> list comprehension on second list together."""

l1 = [1,2,3]
l2 = [4,5,6]
[i*j for i in l1 for j in l2]

