# -*- coding: utf-8 -*-
"""Strings.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ctX25Ui_v1Tdy-TVJX70feeMDyX_ihPV

#LOOP CONTROL STATEMENT

Break

Q.14 Print all the prime numbers between two numbers which will be given by the user as input.
"""

lower = int(input("Enter the lower number: "))
upper = int(input("Enter the upper number: "))

for i in range (lower,upper+1):
  for j in range(2,i):
    if i%j==0:
      break
  else:
    print(i)

"""# STRINGS

Q.15. Find the length of a string without using the len() function.
"""

s =  input("Enter the string: ")
count = 0
for i in s:
  count+=1
  print("Length of the string is:", count)

"""16. Extract username from gmail. (If email is shaan1@gmail.com. then the username should be shaan)"""

s = input("Enter the email:")
pos = s.index('@')
print(s[0:pos])

"""17. Count the frequency of a particular character in a provided string."""

s = input("Enter the string: ")
term = input("Enter the character:")
count = 0
for i in s:
  if i==term:
    count+=1
print("Frequency of the character is:", count)

"""18. Write a program which can remove a particular character from a string.  Note: Since string is immutable we cannot modify it. For this we have to  create a new string."""

s = input("Enter the string: ")
term = input("Enter the character: ")
result = ""
for i in s:
  if i!=term:
    result = result+i
print(result)

"""19. Write a program that can check whether a given string is a palindrome or not?"""

s = input("Enter the string: ")
if s==s[::-1]:
  print("Palindrome")
else:
  print("Not Palindrome")

"""20. write a program to count the number of words in a split without using split()."""

s = input("Enter the string: ")
l = []
temp = " "
for i in s:
  if i!=" ":
    temp = temp+i
  else:
    l.append(temp)
    temp = " "
l.append(temp)
print(l)

"""21. Write a python program to convert an integer to string."""

n = int(input("Enter the number: "))
digits =  '0123456789'
result = " "
while n!=0:
  result = digits[n%10]+result
  n = n//10
print(result)
print(type(result))

"""22.  Write a python program to convert a string to title case without using title() function."""

s = input("Enter the string: ")
l = []
for i in s.split():
  l.append(i[0].upper()+i[1:].lower())
print(" ".join(l))

